import React from 'react';
import { Navigation } from "@/components/Navigation";
import { Footer } from "@/components/Footer";
import { Card } from "@/components/ui/card";

const PrivacyPolicyPage: React.FC = () => {
  const lastUpdatedDate = "April 03, 2024";

  return (
    <div className="min-h-screen flex flex-col">
      <Navigation />
      <main className="flex-grow container mx-auto px-4 py-8 mt-20">
        <Card className="glass-morph p-8 md:p-12 max-w-4xl mx-auto">
          <h1 className="text-3xl md:text-4xl font-bold text-funk-blue text-glow mb-4">
            Privacy Policy
          </h1>
          <p className="text-sm text-funk-grey mb-8">
            Last Updated: {lastUpdatedDate}
          </p>

          <p className="mb-6 text-funk-grey">
            This Privacy Policy describes Our policies and procedures on the collection,
            use and disclosure of Your information when You use the Service and tells You
            about Your privacy rights and how the law protects You.
          </p>
          <p className="mb-6 text-funk-grey">
            We use Your Personal data to provide and improve the Service. By using the
            Service, You agree to the collection and use of information in accordance with
            this Privacy Policy.
          </p>

          {/* Interpretation and Definitions */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-funk-blue mb-3">Interpretation and Definitions</h2>
            <h3 className="text-xl font-semibold text-funk-blue mt-6 mb-2">Interpretation</h3>
            <p className="text-funk-grey">
              The words of which the initial letter is capitalized have meanings defined
              under the following conditions. The following definitions shall have the same
              meaning regardless of whether they appear in singular or in plural.
            </p>
            <h3 className="text-xl font-semibold text-funk-blue mt-6 mb-2">Definitions</h3>
            <p className="mb-4 text-funk-grey">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc list-inside ml-4 space-y-3 text-funk-grey">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to MikePfunk.</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: Massachusetts, United States.</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              <li><strong>Website</strong> refers to MikePfunk, accessible from <a href="https://mikepfunk.com" rel="external nofollow noopener" target="_blank" className="text-funk-blue hover:underline">https://mikepfunk.com</a>.</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
          </section>

          {/* Collecting and Using Your Personal Data */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-funk-blue mb-3">Collecting and Using Your Personal Data</h2>
            <h3 className="text-xl font-semibold text-funk-blue mt-6 mb-2">Types of Data Collected</h3>
            <h4 className="text-lg font-semibold text-funk-blue mt-4 mb-2">Personal Data</h4>
            <p className="text-funk-grey mb-4">
              While using Our Service, We may ask You to provide Us with certain personally
              identifiable information that can be used to contact or identify You.
              Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc list-inside ml-4 space-y-2 text-funk-grey">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="text-lg font-semibold text-funk-blue mt-4 mb-2">Usage Data</h4>
            <p className="text-funk-grey">Usage Data is collected automatically when using the Service.</p>
            <p className="text-funk-grey mt-2">
              Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>

            <h4 className="text-lg font-semibold text-funk-blue mt-4 mb-2">Tracking Technologies and Cookies</h4>
            <p className="text-funk-grey">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.
            </p>
          </section>

          {/* Use of Your Personal Data */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-funk-blue mb-3">Use of Your Personal Data</h2>
            <p className="text-funk-grey mb-4">The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc list-inside ml-4 space-y-3 text-funk-grey">
              <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
              <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
              <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
              <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
              <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events.</li>
              <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
              <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, or other sale or transfer of some or all of Our assets.</li>
            </ul>
          </section>

          {/* Security of Your Personal Data */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-funk-blue mb-3">Security of Your Personal Data</h2>
            <p className="text-funk-grey">
              The security of Your Personal Data is important to Us, but remember that no
              method of transmission over the Internet, or method of electronic storage is
              100% secure. While We strive to use commercially acceptable means to protect
              Your Personal Data, We cannot guarantee its absolute security.
            </p>
          </section>

          {/* Links to Other Websites */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-funk-blue mb-3">Links to Other Websites</h2>
            <p className="text-funk-grey">
              Our Service may contain links to other websites that are not operated by Us.
              If You click on a third party link, You will be directed to that third party's
              site. We strongly advise You to review the Privacy Policy of every site You
              visit. We have no control over and assume no responsibility for the content,
              privacy policies or practices of any third party sites or services.
            </p>
          </section>

          {/* Changes to this Privacy Policy */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-funk-blue mb-3">Changes to this Privacy Policy</h2>
            <p className="text-funk-grey">
              We may update Our Privacy Policy from time to time. We will notify You of any
              changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.
            </p>
          </section>

          {/* Contact Us */}
          <section>
            <h2 className="text-2xl font-semibold text-funk-blue mb-3">Contact Us</h2>
            <p className="text-funk-grey">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <ul className="list-disc list-inside ml-4 mt-2 space-y-2 text-funk-grey">
              <li>By email: <a href="#" onClick={( e ) => { e.preventDefault(); window.location.href = 'mailto:' + 'support' + '@' + 'mikepfunk' + '.com'; }} className="text-funk-blue hover:underline cursor-pointer">{'support' + '@' + 'mikepfunk' + '.com'}</a></li>
            </ul>
          </section>
        </Card>
      </main>
      <Footer />
    </div>
  );
};

export default PrivacyPolicyPage;